name: TogglesDemo

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  XCODE_VERSION: 14.0.1

jobs:
  test:
    name: Build
    runs-on: macos-13
    steps:
    - name: Switch xcode to ${{ env.XCODE_VERSION }}
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
    - name: Show macOS version
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      working-directory: ./TogglesDemo
      run: xcodebuild -list
    - name: Show eligible build destinations for TogglesDemo
      working-directory: ./TogglesDemo
      run: xcodebuild -showdestinations -scheme TogglesDemo
    - name: Build for destination TogglesDemo
      working-directory: ./TogglesDemo
      run: xcodebuild build -scheme TogglesDemo -destination "'platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro'"
