name: TogglesDemo

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  test:
    name: Build for ${{ matrix.destination }}
    runs-on: ${{ matrix.macos }} 
    strategy:
      fail-fast: false
      matrix:
        macos: ['macos-12']
        xcode: ['14.0.1']
        command: ['build']
        scheme: ['TogglesDemo']
        destination: ['platform=iOS Simulator,OS=16.0,name=iPhone 14 Pro']
    steps:
    - name: Switch xcode to ${{ matrix.xcode }}
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
    - name: Show macOS version (${{ matrix.macos }})
      run: sw_vers
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Check xcodebuild version
      run: xcodebuild -version
    - name: Check xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      working-directory: ./TogglesDemo
      run: xcodebuild -list
    - name: Show eligible build destinations for ${{ matrix.scheme }}
      working-directory: ./TogglesDemo
      run: xcodebuild -showdestinations -scheme ${{ matrix.scheme }}
    - name: Build for destination ${{ matrix.destination }}
      working-directory: ./TogglesDemo
      run: xcodebuild ${{ matrix.command }} -scheme ${{ matrix.scheme }} -destination "${{ matrix.destination }}"
