name: ToggleCipher

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  XCODE_VERSION: 14.0.1

jobs:
  test:
    name: Run tests
    runs-on: macos-13
    steps:
    - name: Switch xcode to ${{ env.XCODE_VERSION }}
      run: sudo xcode-select -s /Applications/Xcode_${{ env.XCODE_VERSION }}.app/Contents/Developer
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Run tests
      working-directory: ./ToggleCipher
      run: swift test
