name: Toggles

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  XCODE_VERSION: 14.0.1

jobs:
  test:
    name: Run tests
    runs-on: macos-12
    steps:
    - name: Code Checkout
      uses: actions/checkout@v2
    - name: Select Xcode
      uses: ./.github/actions/select-xcode
      with:
        xcode-version: ${{ env.XCODE_VERSION }}
    - name: Run tests
      run: swift test
